#include <stdio.h>
#include <windows.h>
#include <winioctl.h>
#include "pe64.h"
#include "SymbolFind.h"
#include "resource.h"


#define SET_RANGE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define STOP_TRACER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define INIT_HOOKS  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define REF_EVENT   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GET_STATE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x840, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SET_STATE   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x850, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SET_MMACCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x860, METHOD_BUFFERED, FILE_ANY_ACCESS)


typedef struct{
	ULONG	pid;
	ULONG	address;
	ULONG	size;
}TRACER, *PTRACER;

#define s_wait    0x1
#define s_ready   0x2

typedef struct{
        ULONG   eip;
        ULONG   state;
}TRACER_DATA, *PTRACER_DATA; 
